#!/bin/bash
score_report="/home/jack/Desktop/ScoreReport.html"
function check()
{
        if ( eval $1 ); then
                if (cat $score_report | grep $2); then
                        sed -i "$3/$2/$4/g" $score_report
                fi
        elif ( ! eval $1 ); then 
                if (! cat $score_report | "grep $2</p>"); then
                        sed -i "$3/$4/$2/g" $score_report
                fi
        fi
}

check 'cat /home/cyber/Desktop/Forensics_1 | grep "L0y0l@B3@t$H@ll"' 'vuln1' '19s' 'Forensics 1 Correct'
check 'cat /home/cyber/Desktop/Forensics_2 | grep "L0y0l@B3@t$H@ll"' 'vuln2' '20s' 'Forensics 2 Correct'
check 'cat /etc/group | grep "Ginger"' 'vuln3' '21s' 'User Ginger removed'
check '! cat /etc/group | grep "sudo" | grep "Will"' 'vuln4' '22s' 'User Will is not an admin'
check 'cat /etc/group | grep "Training_Leads"' 'vuln5' '23s' 'Group Training_Leads added'
check 'cat /etc/group | grep "Training_Leads" | grep "James"' 'vuln6' '24s' 'User James added to group Training_Leads'
check 'ufw status | grep "active"' 'vuln7' '25s' 'Firewall turned on'
check 'ufw status | grep "active" | grep "high"' 'vuln8' '26s' 'Firewall logging set to high'
check 'cat /etc/login.defs | grep "PASS_MAX_DAYS" | grep "90"' 'vuln9' '27s' 'Maximum password age set'
check 'cat /etc/pam.d/common-password | grep "unix.so" | grep "minlen=16"' 'vuln10' '27s' 'Minimum password length set'
check 'cat /etc/pam.d/common-auth | grep "retry=5"' 'vuln11' '28s' 'Maximum number of login attempts set'
check '! cat /etc/sudoers | grep "Ginger"' 'vuln3' '21s' 'User Ginger removed'
